# @name POST
POST http://127.0.0.1:3333/events
#Headers
Content-Type: application/json 

#Content Request Body
{

    "title": "Unite Summit Dev 2024",
    "details": "Um evento para quem é apaixonado por programação e tecnologia",
    "maximumAttendees": 100

}